apiVersion: v1
kind: Secret
metadata:
  name: {{ include "wicklee.fullname" . }}-env
  labels:
    {{- include "wicklee.labels" . | nindent 4 }}
type: Opaque
stringData:
  DATABASE_URL: {{ include "wicklee.databaseUrl" . | quote }}
  WICKLEE_LICENSE_KEY: {{ .Values.config.licenseKey | quote }}
  CLERK_JWKS_URL: {{ .Values.config.clerkJwksUrl | quote }}
  CLERK_SECRET_KEY: {{ .Values.config.clerkSecretKey | quote }}
  RESEND_API_KEY: {{ .Values.config.resendApiKey | quote }}
  FROM_EMAIL: {{ .Values.config.fromEmail | quote }}
  HUGGINGFACE_TOKEN: {{ .Values.config.huggingfaceToken | quote }}
